language: node_js
node_js:
  - "8.9.4"

branches:
  only:
    - develop

before_script:
  - npm install -g @angular/cli

script:
  - ng build 

after_success:
  - chmod +x scripts/ci/post-build.sh
  - ./scripts/ci/post-build.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: false
  on:
    branch: develop
  local_dir: dist
